### ISSUE TITLE
Reconstruction Jupyter Notebook errors

### ISSUE THREAD

**Issue by mikephelan** [opendifferentialprivacy/smartnoise-samples#69]
ModuleNotFoundError: No module named 'opendp.whitenoise'
ModuleNotFoundError: No module named 'z3'

Fix is underway

**Comment by raprasad** [comment]
From #68 The code is out of date with current bindings:

https://github.com/opendifferentialprivacy/smartnoise-samples/tree/master/attacks/reconstruction
(This may also get wrapped into the auto-generation of notebooks)
